name: Build Artifacts

on:
  push:
    branches: [ "support/*", "dev/*" ]
#    tags:
#      - 'v*'
#      - '*'

jobs:
  build:
    name: "Build plugin and publish to repo"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Copy Maven settings
        run: cp .m2/settings.xml ~/.m2/settings.xml

      - name: Publish to GitHub Packages
        run: mvn -B deploy -DskipTests -Pgithub-deploy --file pom.xml
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
